routes/web.php
<?php

use App\Http\Controllers\ArtisanController;
use App\Http\Controllers\BotUserInfoController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\DriverStatusController;
use App\Http\Controllers\Dsp\LoadController as DspLoadController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LoadController;
use App\Http\Controllers\PaymentGatewayController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StatsController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TelegramBotController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TrailerController;
use App\Http\Controllers\UserController;
use App\Http\Middleware\IsAdmin;
use App\Http\Middleware\IsDsp;
use App\Http\Middleware\IsManager;
use App\Http\Middleware\IsQc;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// telegram bot
Route::post('telegram-bot-r91zh779lfm7h8tq', [TelegramBotController::class, 'index'])->name('telegram-bot');
Route::get('telegram-bot/sethook-r91zh779lfm7h8tq', [TelegramBotController::class, 'sethook'])->name('telegram-bot.sethook');
Route::get('telegram-bot/deletehook-r91zh779lfm7h8tq', [TelegramBotController::class, 'deletehook'])->name('telegram-bot.deletehook');

// Payment
Route::post('paycom-emkooolkztfbzciw', [PaymentGatewayController::class, 'paycom'])->name('payment-gateway.paycom');
Route::any('click-pnhhqhfniksaejcn/prepare', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.prepare');
Route::any('click-pnhhqhfniksaejcn/complete', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.complete');

// Test
Route::get('test', [TestController::class, 'index']);

// report
Route::get('loads/report/daily-d778a0jdb29r', [LoadController::class, 'report'])->name('loads.report.daily.public');

Route::group(['middleware' => ['auth']], function () {

    // common routes
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('profile/update/password', [ProfileController::class, 'updatePassword'])->name('profile.update.password');

    // admin routes
    Route::group(['middleware' => [IsAdmin::class]], function () {
        Route::get('stats/drivers', [StatsController::class, 'drivers'])->name('stats.drivers');
        Route::resource('bot-user-info', BotUserInfoController::class);
        Route::resource('teams', TeamController::class);
        Route::resource('trailers', TrailerController::class);
        Route::get('drivers/{driver}/stats', [DriverController::class, 'stats'])->name('drivers.stats');
        Route::get('drivers/{driver}/history', [DriverController::class, 'history'])->name('drivers.history');
        Route::resource('drivers', DriverController::class);
        Route::get('loads', [LoadController::class, 'index'])->name('loads.index');
        Route::delete('loads/{load}', [LoadController::class, 'destroy'])->name('loads.destroy');
        Route::get('loads/download', [LoadController::class, 'download'])->name('loads.download');
        Route::get('loads/report', [LoadController::class, 'report'])->name('loads.report');

        Route::get('driver-statuses', [DriverStatusController::class, 'index'])->name('driver-statuses.index');
        Route::get('driver-statuses/{driverStatus}/edit', [DriverStatusController::class, 'edit'])->name('driver-statuses.edit');
        Route::put('driver-statuses/{driverStatus}', [DriverStatusController::class, 'update'])->name('driver-statuses.update');
        Route::delete('driver-statuses/{driverStatus}', [DriverStatusController::class, 'destroy'])->name('driver-statuses.destroy');

        Route::resource('users', UserController::class);
        Route::post('images', [ImageController::class, 'store'])->name('images.store');
        Route::resource('settings', SettingController::class);
    });

    // manager routes
    Route::group(['middleware' => [IsManager::class]], function () {
        //
    });

    // dsp routes
    Route::group(['middleware' => [IsDsp::class]], function () {
        //
    });

    // qc routes
    Route::group(['middleware' => [IsQc::class]], function () {
        //
    });

    // common boards
    Route::get('board', [HomeController::class, 'board'])->name('board');
    Route::get('team-sheet', [HomeController::class, 'teamSheet'])->name('team-sheet');
    Route::get('kpi-board', [HomeController::class, 'kpiBoard'])->name('kpi-board');
    Route::get('drivers-board', [HomeController::class, 'driversBoard'])->name('drivers-board');

    // loads
    Route::get('loads/{load}/cancel', [LoadController::class, 'cancelCreate'])->name('loads.cancel');
    Route::post('loads/{load}/cancel', [LoadController::class, 'cancelStore']);
    Route::get('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmCreate'])->name('loads.edit.confirm');
    Route::put('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmStore']);
    Route::get('loads/{load}', [LoadController::class, 'show'])->name('loads.show');
    Route::get('loads/{load}/edit', [LoadController::class, 'edit'])->name('loads.edit');
    Route::put('loads/{load}', [LoadController::class, 'update'])->name('loads.update');

    // artisan
    Route::get('artisan/migrate', [ArtisanController::class, 'migrate']);
    Route::get('artisan/driver/status-update', [ArtisanController::class, 'driverStatusUpdate']);
    Route::get('artisan/driver/create-weekly-plan', [ArtisanController::class, 'driverCreateWeeklyPlan']);
});

Auth::routes(['register' => false, 'reset' => false]);

app/Models/Driver.php
<?php

namespace App\Models;

use App\Helpers\Helper;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class Driver extends Model
{
    use HasFactory;

    const W_TARGET = 10000;
    const REST_TIME = 180;

    const TYPE_COMPANY = '*C';
    const TYPE_OWNER = '*O';
    const TYPE_OWNER_OWNER = '*OO';
    const TYPE_RENTAL = '*R';
    const TYPE_LEASE = '*L';
    const TYPE_CP = '*CP';

    protected $guarded = [];

    protected $casts = [
        'birthday' => 'date',
    ];

    protected static function booted()
    {
        static::saving(function ($driver) {
            $addressParsed = Helper::parseAddress($driver->home_address);
            $driver->home_address_state_code = $addressParsed['state'];
            $driver->home_address_zip_code = $addressParsed['zip'];
        });
        static::saved(function ($driver) {
            if ($driver->isDirty('dispatcher_id')) {
                Changelog::create([
                    'driver_id' => $driver->id,
                    'dispatcher_id' => $driver->dispatcher_id,
                    'message' => __('New dispatcher') . ($driver->dispatcher ? ' ' . $driver->dispatcher->botUserInfo->full_name : ''),
                ]);
            }
        });
    }

    public function loads()
    {
        return $this->hasMany(Load::class);
    }

    public function driverStatuses()
    {
        return $this->hasMany(DriverStatus::class);
    }

    public function relatedload()
    {
        return $this->belongsTo(Load::class, 'load_id');
    }

    public function trailer()
    {
        return $this->belongsTo(Trailer::class);
    }

    public function driverPlans()
    {
        return $this->hasMany(DriverPlan::class);
    }

    public function dispatcher()
    {
        return $this->belongsTo(BotUser::class, 'dispatcher_id');
    }

    public function additionalDispatchers()
    {
        return $this->belongsToMany(BotUser::class, 'driver_dispatchers', 'driver_id', 'dispatcher_id');
    }

    public function getDispatcherNameAttribute()
    {
        $name = '';
        if ($this->dispatcher && $this->dispatcher->botUserInfo) {
            $name = $this->dispatcher->botUserInfo->full_name;
        }

        return $name;
    }

    public function getDispatchersNamesAttribute()
    {
        $names = [];
        if ($this->dispatcher) {
            $names[] = $this->dispatcher->botUserInfo->full_name;
        }
        foreach ($this->additionalDispatchers as $dispatcher) {
            $names[] = $dispatcher->botUserInfo->full_name;
        }

        return implode(', ', $names);
    }

    public function getAdditionalDispatchersNamesAttribute()
    {
        $names = [];
        foreach ($this->additionalDispatchers as $dispatcher) {
            if (!$dispatcher->botUserInfo) {
                continue;
            }
            $names[] = $dispatcher->botUserInfo->full_name;
        }
        return implode(', ', $names);
    }

    public function latestDriverStatus()
    {
        if (!$this->relationLoaded('driverStatuses')) {
            $this->load('driverStatuses');
        }
        $driverStatus = $this->driverStatuses->sortByDesc('id')->first();
        if (!$driverStatus) {
            $driverStatus = $this->driverStatuses()->create([
                'status' => DriverStatus::STATUS_READY_1,
                'start_time' => now(),
                'end_time' => now()->addHours(3),
            ]);
        }
        return $driverStatus;
    }

    public function currentDriverStatus()
    {
        return $this->belongsTo(DriverStatus::class, 'current_driver_status_id');
    }

    public function getCurrentDriverStatus(CarbonInterface $date = null)
    {
        if (!$this->relationLoaded('driverStatuses')) {
            $this->load(['driverStatuses' => function ($q) {
                $q->where('start_time', '>=', now()->subMonth())->with('relatedLoad');
            }]);
        }
        $current = false;
        if (!$date) {
            $current = true;
            $date = now();
        }

        $filtered = $this->driverStatuses->filter(function ($driverStatus) use ($date) {
            $isActive = false;
            if ($driverStatus->start_time <= $date && ($driverStatus->end_time >= $date || $driverStatus->end_time == null)) {
                $isActive = true;
            }
            return $isActive;
        });


        $driverStatus = $filtered->sortByDesc('id')->first();

        if (!$driverStatus && $current) {
            // check latest if ready 1 next is ready 2, elseif ready 2 next is ready3 else ready1
            $latestDriverStatus = $this->driverStatuses->sortByDesc('id')->first();
            $nextStatus = DriverStatus::STATUS_READY_1;
            $endTime = now()->addHours(3);
            $latestLoadId = !empty($latestDriverStatus->load_id) ? $latestDriverStatus->load_id : null;
            if ($latestDriverStatus && $latestDriverStatus->isReady1()) {
                $nextStatus = DriverStatus::STATUS_READY_2;
                $endTime = now()->addHours(2);
            } elseif ($latestDriverStatus && $latestDriverStatus->isReady2()) {
                $nextStatus = DriverStatus::STATUS_READY_3;
                $endTime = now()->addHours(6);
            } elseif ($latestDriverStatus && $latestDriverStatus->isReady3()) {
                $nextStatus = DriverStatus::STATUS_READY_3;
                $endTime = now()->addHours(6);
            }
            $driverStatus = $this->driverStatuses()->create([
                'load_id' => $latestLoadId,
                'status' => $nextStatus,
                'start_time' => now(),
                'end_time' => $endTime,
            ]);
        }
        return $driverStatus;
    }

    public function getStatusTitleAttribute()
    {
        return DriverStatus::statuses()[$this->status];
    }

    public function getStatusColorAttribute()
    {
        return DriverStatus::statusColors()[$this->status];
    }

    public function getNameAndIdAttribute()
    {
        return $this->name . ' (ID: ' . $this->id . ')';
    }

    public function updateStatus()
    {
        $now = now();
        $driverStatus = $this->getCurrentDriverStatus();

        if (!$driverStatus) {
            return;
        }

        if ($driverStatus->isShop()) {
            // nothing required, only driver status will be updated
        } elseif ($driverStatus->isRest() || $driverStatus->isHome() || $driverStatus->isVacation()) {
            // check current status ended and set next
            if ($driverStatus->end_time != null && $now > $driverStatus->end_time) {
                $upcomingLoad = $this->loads()->active()->where('pickup_time', '>=', $driverStatus->end_time)->orderBy('pickup_time')->first();
                // set next status
                if ($upcomingLoad && $upcomingLoad->pickup_time > $now) {
                    // next status dispatched
                    $driverStatus = DriverStatus::firstOrCreate([
                        'driver_id' => $this->id,
                        'load_id' => $upcomingLoad->id,
                        'trailer_id' => $upcomingLoad->trailer_id,
                        'status' => DriverStatus::STATUS_DISPATCHED,
                        'start_time' => $driverStatus->end_time,
                        'end_time' => $upcomingLoad->pickup_time,
                    ]);
                } elseif ($upcomingLoad && $upcomingLoad->pickup_time <= $now) {
                    // next status transit
                    $driverStatus = DriverStatus::firstOrCreate([
                        'driver_id' => $this->id,
                        'load_id' => $upcomingLoad->id,
                        'trailer_id' => $upcomingLoad->trailer_id,
                        'status' => DriverStatus::STATUS_TRANSIT,
                        'start_time' => $driverStatus->end_time,
                        'end_time' => $upcomingLoad->delivery_time,
                    ]);
                } else {
                    $driverStatus = DriverStatus::firstOrCreate([
                        'driver_id' => $this->id,
                        'status' => DriverStatus::STATUS_READY_1,
                        'start_time' => $driverStatus->end_time,
                        'end_time' => (clone $driverStatus->end_time)->addHours(3),
                    ]);
                }
            }
        } elseif ($driverStatus->isReady()) {
            // check current status ended and set next
            $upcomingLoad = $this->loads()->active()->where('pickup_time', '>=', $driverStatus->end_time)->orderBy('pickup_time')->first();
            $currentLoad = $this->loads()->active()->where('pickup_time', '<=', now())->where('delivery_time', '>=', now())->orderBy('pickup_time')->first();

            // set next status
            if ($upcomingLoad) {
                $driverStatus->end_time = $now;
                $driverStatus->save();
                // next status dispatched
                if ($upcomingLoad->pickup_time > $now) {
                    $driverStatus = DriverStatus::firstOrCreate([
                        'driver_id' => $this->id,
                        'load_id' => $upcomingLoad->id,
                        'trailer_id' => $upcomingLoad->trailer_id,
                        'status' => DriverStatus::STATUS_DISPATCHED,
                        'start_time' => $now,
                        'end_time' => $upcomingLoad->pickup_time,
                    ]);
                } else {
                    $driverStatus = DriverStatus::firstOrCreate([
                        'driver_id' => $this->id,
                        'load_id' => $upcomingLoad->id,
                        'trailer_id' => $upcomingLoad->trailer_id,
                        'status' => DriverStatus::STATUS_TRANSIT,
                        'start_time' => $now,

app/Http/Controllers/Api/DriverController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\BotUserInfo;
use App\Models\Driver;
use App\Models\Team;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

class DriverController extends Controller
{
    public function timeline(Request $request, Driver $driver)
    {
        //
    }
}

resources/views/drivers/create.blade.php
@extends('layouts.app')

@section('title', __('Add driver'))

@section('content')
    <div class="container">

        <h1>{{ __('Add driver') }}</h1>

        <div class="py-4">
            <a href="{{ (url()->previous() && url()->previous() != url()->current()) ? url()->previous() : route('drivers.index') }}" class="btn btn-info">{{ __('Back') }}</a>
        </div>

        <form action="{{ route('drivers.store') }}" method="POST">

            @csrf

            @include('drivers.partials.form')

            <div class="form-group">
                <button class="btn btn-lg btn-success" type="submit">{{ __('Save') }}</button>
            </div>
        </form>

    </div>
@endsection

resources/views/drivers/edit.blade.php
@extends('layouts.app')

@section('title', __('Edit driver'))

@section('content')
    <div class="container">

        <h1>{{ __('Edit driver') }}</h1>

        <div class="py-4">
            <a href="{{ (url()->previous() && url()->previous() != url()->current()) ? url()->previous() : route('drivers.index') }}" class="btn btn-info">{{ __('Back') }}</a>
        </div>

        <form action="{{ route('drivers.update', $driver->id) }}" method="POST">

            @csrf
            @method('PUT')

            @include('drivers.partials.form')

            <div class="form-group">
                <button class="btn btn-lg btn-success" type="submit">{{ __('Save') }}</button>
            </div>
        </form>

    </div>
@endsection

resources/views/drivers/history.blade.php
@extends('layouts.app')

@section('title', __('Driver') . ' ' . $driver->name . ' ' . __('History'))

@section('content')
    <div class="container">

    	<h1>
    		{{ __('Driver') }} {{ $driver->name }} {{ __('History') }}
    	</h1>

        <div class="py-4 d-print-none">
            <a href="{{ (url()->previous() && url()->previous() != url()->current()) ? url()->previous() : route('drivers.index') }}" class="btn btn-info">{{ __('Back') }}</a>
        </div>

        <div class="table-responsive">
            <table class="table table-bordered table-light table-hover">
                <tr class="table-active">
                    <th>
                        {{ __('Date') }}
                    </th>
                    <th>
                        {{ __('Message') }}
                    </th>
                </tr>
                @forelse($changelogs as $changelog)
                    <tr>
                        <td>{{ Helper::formatDateTime($changelog->created_at) }}</td>
                        <td>{{ $changelog->message }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2" class="text-center">{{ __('Nothing found') }}</td>
                    </tr>
                @endforelse
            </table>
        </div>


        <br>
        <br>
        <br>
        <br>
        <br>

    </div>
@endsection

resources/views/drivers/index.blade.php
@extends('layouts.app')

@section('title', __('Drivers'))

@section('content')
    <div class="container-fluid">

        @include('partials.alerts')

        <div class="my-4">
            <div class="table-responsive">
                <table class="table table-light table-bordered table-hover">
                    <tr class="table-active">
                        <th>{{ __('Drivers') }}</th>
                    </tr>
                    <tr>
                        <td>
                            <strong>All: {{ $drivers->total() }}</strong> <br>
                            Active: {{ $activeDriversQty }}
                        </td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="my-4">
            <a href="{{ route('drivers.create') }}" class="btn btn-lg btn-info">
                {{ __('Add driver') }}
            </a>
            <a href="{{ route('stats.drivers') }}" class="btn btn-lg btn-primary">
                {{ __('Stats') }}
            </a>
        </div>

        <h1>{{ __('Drivers') }}</h1>

        <div class="my-4">
            <form action="{{ route('drivers.index') }}" id="drivers-filter-form">

                <div class="row">
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <div class="form-group">
                                <label for="form_name">{{ __('Name') }}</label>
                                <input type="text" id="form_name" name="name" class="form-control"
                                    value="{{ $filter['name'] }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <div class="form-group">
                                <label for="form_truck_number">{{ __('Truck number') }}</label>
                                <input type="text" id="form_truck_number" name="truck_number" class="form-control"
                                    value="{{ $filter['truck_number'] }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <label for="form_status">{{ __('Status') }}</label>
                            <select class="form-control" name="status" id="form_status">
                                <option value="-">-</option>
                                @foreach ($statuses as $key => $value)
                                    <option value="{{ $key }}" @if ((string) $key == $filter['status']) selected @endif>
                                        {{ $value }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <button class="btn btn-primary" type="submit">{{ __('Apply filter') }}</button>
                </div>
            </form>
        </div>

        <div class="my-4">
            <div class="table-responsive">
                <table class="table table-bordered table-light table-hover">
                    <tr class="table-active">
                        <th>
                            {{ __('ID') }}
                        </th>
                        <th>
                            {{ __('Name') }}
                        </th>
                        <th>
                            {{ __('Phone number') }}
                        </th>
                        <th>
                            {{ __('Chat ID') }}
                        </th>
                        <th>
                            {{ __('Truck number') }}
                        </th>
                        <th>
                            {{ __('Payment') }}
                        </th>
                        <th>
                            {{ __('Created time') }}
                        </th>
                        <th>
                            {{ __('Weekly target rate') }}
                        </th>
                        <th>
                            {{ __('Weekly target mile') }}
                        </th>
                        <th>
                            {{ __('Main dispatcher') }}
                        </th>
                        <th>
                            {{ __('Additional dispatchers') }}
                        </th>
                        <th>
                            {{ __('Status') }}
                        </th>
                        <th>
                            {{ __('Active') }}
                        </th>
                        <th>
                            {{ __('Home address') }}
                        </th>
                        <th></th>
                    </tr>
                    @forelse($drivers as $driver)
                        <tr>
                            <td>{{ $driver->id }}</td>
                            <td>
                                {{ $driver->name }} <br>
                                {{ $driver->type_title }}
                            </td>
                            <td>{{ $driver->phone_number }}</td>
                            <td>
                                <div>{{ $driver->chat_id ?? '-' }}</div>
                                <div>
                                    <span id="chat-bind-code-{{ $driver->id }}">{{ $driver->chat_bind_code }}</span>
                                </div>
                                <div>
                                    <button type="button" class="btn btn-sm btn-primary copy-btn" data-content="Copied"
                                        data-target="#chat-bind-code-{{ $driver->id }}"><i
                                            class="fa-regular fa-copy"></i> Copy code</button>
                                </div>
                            </td>
                            <td>{{ $driver->truck_number }}</td>
                            <td>
                                <div>
                                    {{ __('Pay per mile') }}: {{ $driver->pay_per_mile }}
                                </div>
                                <div>
                                    {{ __('Penske pay per mile') }}: {{ $driver->penske_pay_per_mile }}
                                </div>
                                <div>
                                    {{ __('Fixed cost') }}: {{ $driver->fixed_cost }}
                                </div>
                            </td>
                            <td>{{ Helper::formatDateTime($driver->created_at) }}</td>
                            <td>{{ $driver->weekly_target }}</td>
                            <td>{{ $driver->weekly_target_mile }}</td>
                            <td>{{ $driver->dispatcher_name }}</td>
                            <td>{{ $driver->additional_dispatchers_names }}</td>
                            <td>{{ $driver->status_title }}</td>
                            <td>{{ $driver->active ? __('Yes') : __('No') }}</td>
                            <td>{{ $driver->home_address }}</td>
                            <td class="text-nowrap">
                                <a href="{{ route('drivers.edit', ['driver' => $driver->id]) }}"
                                    class="btn btn-sm btn-warning">{{ __('Edit') }}</a>
                                <a href="{{ route('drivers.stats', ['driver' => $driver->id]) }}"
                                    class="btn btn-sm btn-primary">{{ __('Stats') }}</a>
                                <a href="{{ route('driver-statuses.index', ['driver_id' => $driver->id]) }}"
                                    class="btn btn-sm btn-info">{{ __('Status') }}</a>
                                <a href="{{ route('drivers.history', ['driver' => $driver->id]) }}"
                                    class="btn btn-sm btn-info">{{ __('History') }}</a>
                                @if (!$driver->isActive())
                                    <a href="javascript:;"
                                        onclick="confirm('{{ __('Are you sure?') }}') && $('#delete-driver-{{ $driver->id }}').submit()"
                                        class="btn btn-sm btn-danger">{{ __('Delete') }}</a>
                                    <form action="{{ route('drivers.destroy', ['driver' => $driver->id]) }}" method="post"
                                        id="delete-driver-{{ $driver->id }}">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                @endif

                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="15" class="text-center">{{ __('Nothing found') }}</td>
                        </tr>
                    @endforelse
                </table>
            </div>
            {{ $drivers->withQueryString()->links() }}
        </div>


        <br>
        <br>
        <br>
        <br>
        <br>

    </div>
@endsection

resources/views/drivers/show.blade.php
@extends('layouts.app')

@section('title', __('Driver') . '#' . $driver)

@section('content')
    <div class="container">

    	<h1>
    		{{ __('Driver') }} #{{ $driver }}
    	</h1>

        <div class="py-4 d-print-none">
            <a href="{{ (url()->previous() && url()->previous() != url()->current()) ? url()->previous() : route('drivers.index') }}" class="btn btn-info">{{ __('Back') }}</a>
        </div>

    </div>
@endsection