routes/web.php
<?php

use App\Http\Controllers\ArtisanController;
use App\Http\Controllers\BotUserInfoController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\DriverStatusController;
use App\Http\Controllers\Dsp\LoadController as DspLoadController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LoadController;
use App\Http\Controllers\PaymentGatewayController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StatsController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TelegramBotController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TrailerController;
use App\Http\Controllers\UserController;
use App\Http\Middleware\IsAdmin;
use App\Http\Middleware\IsDsp;
use App\Http\Middleware\IsManager;
use App\Http\Middleware\IsQc;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// telegram bot
Route::post('telegram-bot-r91zh779lfm7h8tq', [TelegramBotController::class, 'index'])->name('telegram-bot');
Route::get('telegram-bot/sethook-r91zh779lfm7h8tq', [TelegramBotController::class, 'sethook'])->name('telegram-bot.sethook');
Route::get('telegram-bot/deletehook-r91zh779lfm7h8tq', [TelegramBotController::class, 'deletehook'])->name('telegram-bot.deletehook');

// Payment
Route::post('paycom-emkooolkztfbzciw', [PaymentGatewayController::class, 'paycom'])->name('payment-gateway.paycom');
Route::any('click-pnhhqhfniksaejcn/prepare', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.prepare');
Route::any('click-pnhhqhfniksaejcn/complete', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.complete');

// Test
Route::get('test', [TestController::class, 'index']);

// report
Route::get('loads/report/daily-d778a0jdb29r', [LoadController::class, 'report'])->name('loads.report.daily.public');

Route::group(['middleware' => ['auth']], function () {

    // common routes
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('profile/update/password', [ProfileController::class, 'updatePassword'])->name('profile.update.password');

    // admin routes
    Route::group(['middleware' => [IsAdmin::class]], function () {
        Route::get('stats/drivers', [StatsController::class, 'drivers'])->name('stats.drivers');
        Route::resource('bot-user-info', BotUserInfoController::class);
        Route::resource('teams', TeamController::class);
        Route::resource('trailers', TrailerController::class);
        Route::get('drivers/{driver}/stats', [DriverController::class, 'stats'])->name('drivers.stats');
        Route::get('drivers/{driver}/history', [DriverController::class, 'history'])->name('drivers.history');
        Route::resource('drivers', DriverController::class);
        Route::get('loads', [LoadController::class, 'index'])->name('loads.index');
        Route::delete('loads/{load}', [LoadController::class, 'destroy'])->name('loads.destroy');
        Route::get('loads/download', [LoadController::class, 'download'])->name('loads.download');
        Route::get('loads/report', [LoadController::class, 'report'])->name('loads.report');

        Route::get('driver-statuses', [DriverStatusController::class, 'index'])->name('driver-statuses.index');
        Route::get('driver-statuses/{driverStatus}/edit', [DriverStatusController::class, 'edit'])->name('driver-statuses.edit');
        Route::put('driver-statuses/{driverStatus}', [DriverStatusController::class, 'update'])->name('driver-statuses.update');
        Route::delete('driver-statuses/{driverStatus}', [DriverStatusController::class, 'destroy'])->name('driver-statuses.destroy');

        Route::resource('users', UserController::class);
        Route::post('images', [ImageController::class, 'store'])->name('images.store');
        Route::resource('settings', SettingController::class);
    });

    // manager routes
    Route::group(['middleware' => [IsManager::class]], function () {
        //
    });

    // dsp routes
    Route::group(['middleware' => [IsDsp::class]], function () {
        //
    });

    // qc routes
    Route::group(['middleware' => [IsQc::class]], function () {
        //
    });

    // common boards
    Route::get('board', [HomeController::class, 'board'])->name('board');
    Route::get('team-sheet', [HomeController::class, 'teamSheet'])->name('team-sheet');
    Route::get('kpi-board', [HomeController::class, 'kpiBoard'])->name('kpi-board');
    Route::get('drivers-board', [HomeController::class, 'driversBoard'])->name('drivers-board');

    // loads
    Route::get('loads/{load}/cancel', [LoadController::class, 'cancelCreate'])->name('loads.cancel');
    Route::post('loads/{load}/cancel', [LoadController::class, 'cancelStore']);
    Route::get('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmCreate'])->name('loads.edit.confirm');
    Route::put('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmStore']);
    Route::get('loads/{load}', [LoadController::class, 'show'])->name('loads.show');
    Route::get('loads/{load}/edit', [LoadController::class, 'edit'])->name('loads.edit');
    Route::put('loads/{load}', [LoadController::class, 'update'])->name('loads.update');

    // artisan
    Route::get('artisan/migrate', [ArtisanController::class, 'migrate']);
    Route::get('artisan/driver/status-update', [ArtisanController::class, 'driverStatusUpdate']);
    Route::get('artisan/driver/create-weekly-plan', [ArtisanController::class, 'driverCreateWeeklyPlan']);
});

Auth::routes(['register' => false, 'reset' => false]);

app/Models/Load.php
<?php

namespace App\Models;

use App\Helpers\Helper;
use App\Services\TelegramService;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Load extends Model
{
    use HasFactory;

    const TYPE_MARKET_SPOT = 0;
    const TYPE_AMAZON_SPOT = 1;
    const TYPE_MARKET_DEDICATED = 2;
    const TYPE_AMAZON_DEDICATED = 3;
    const TYPE_LOAD_REPOWERED_SELF_TRUCK = 4;
    const TYPE_LOAD_REPOWERED_THIRD_PARTY = 5;
    const TYPE_LOAD_RECOVERED_SELF_TRUCK = 6;
    const TYPE_LOAD_RECOVERED_THIRD_PARTY = 7;

    const STATUS_OVERWRITTEN = -2;
    const STATUS_CANCELLED = -1;
    const STATUS_CREATED = 0;
    const STATUS_CONFIRMED = 1;
    const STATUS_RECONFIRMED = 2;

    const FILE_TYPE_PHOTO = 0;
    const FILE_TYPE_DOCUMENT = 1;

    const TRANSIT_MAX_DAYS = 3;

    protected $guarded = [];

    protected $casts = [
        'local_pickup_time' => 'datetime',
        'pickup_time' => 'datetime',
        'local_delivery_time' => 'datetime',
        'delivery_time' => 'datetime',
        'pickup_time_for_driver' => 'datetime',
        'delivery_time_for_driver' => 'datetime',
    ];

    protected static function booted()
    {
        static::saving(function ($load) {
            $load->mile = $load->countTotalMile();
            $load->total = $load->countTotalRate();
            $load->pickup_time = Helper::convertToBotTime($load->local_pickup_time, $load->pickup_timezone);
            $load->delivery_time = Helper::convertToBotTime($load->local_delivery_time, $load->delivery_timezone);

            $load->batch_number = Helper::getLoadBatchNumber($load);

            $pickupAddressParsed = Helper::parseAddress($load->pickup_location);
            $load->pickup_state_code = $pickupAddressParsed['state'];
            $load->pickup_zip_code = $pickupAddressParsed['zip'];

            $deliveryAddressParsed = Helper::parseAddress($load->delivery_location);
            $load->delivery_state_code = $deliveryAddressParsed['state'];
            $load->delivery_zip_code = $deliveryAddressParsed['zip'];
        });

        static::created(function ($load) {
            // send notification to history group
            $telegram = new TelegramService();
            // send file photo/pdf
            $historyGroupChatId = Helper::setting('history_group');
            if ($load->file_type == Load::FILE_TYPE_PHOTO) {
                $telegram->sendPhoto($historyGroupChatId, $load->file_id);
            } elseif ($load->file_type == Load::FILE_TYPE_DOCUMENT) {
                $telegram->sendDocumentById($historyGroupChatId, $load->file_id);
            }
            // send message
            $telegram->sendMessage($historyGroupChatId, $load->generateInfoTelegram());


            // send notifications to driver group (dispatch confirmation) #LoadID and #MileageInfo
            $dispatchConfirmationText = $load->dispatchInfoTelegram();
            $testingGroupChatId = Helper::setting('temporary_testing_group');
            $driverGroupChatId = $load->driver ? $load->driver->chat_id : null;
            $telegram->sendMessage($testingGroupChatId, $dispatchConfirmationText, 'HTML');
            if ($driverGroupChatId) {
                $telegram->sendMessage($driverGroupChatId, $dispatchConfirmationText, 'HTML');
            }
            $mileageInfoText = $load->mileageInfoTelegram();
            $telegram->sendMessage($testingGroupChatId, $mileageInfoText, 'HTML');
            if ($driverGroupChatId) {
                $telegram->sendMessage($driverGroupChatId, $mileageInfoText, 'HTML');
            }

            /**#MileageInfo
Batch No.: 328

Authorized loaded mile:
DH mile:
Other miles:
______________________________
Total miles:

@DriverName
 */

        });
        static::saved(function ($load) {
            // update driver status after cancelled
            if ($load->cancel_time) {
                if ($load->cancel_time <= $load->pickup_time) {
                    DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_TRANSIT)->delete();
                } elseif ($load->cancel_time > $load->pickup_time && $load->cancel_time < $load->delivery_time) {
                    DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_TRANSIT)->update([
                        'end_time' => $load->cancel_time,
                    ]);
                }
            }

            // update transit driver status if pickup_time and
            $transitDriverStatus = DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_TRANSIT)->latest()->first();
            if ($transitDriverStatus) {
                $transitDriverStatus->start_time = $load->pickup_time;
                $transitDriverStatus->end_time = $load->delivery_time;
                $transitDriverStatus->saveQuietly();
            }
            $dispatchedDriverStatus = DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_DISPATCHED)->latest()->first();
            if ($dispatchedDriverStatus) {
                $dispatchedDriverStatus->end_time = $load->pickup_time;
                $dispatchedDriverStatus->saveQuietly();
            }
        });
    }

    public function driver()
    {
        return $this->belongsTo(Driver::class);
    }

    public function mainTrailer()
    {
        return $this->belongsTo(Trailer::class, 'trailer_id');
    }

    public function getDriverNameAttribute()
    {
        $name = '-';
        if ($this->driver) {
            $name = $this->driver->name;
        }
        return $name;
    }

    public function assignedDspBotUser()
    {
        return $this->belongsTo(BotUser::class, 'assigned_dsp_bot_user_id');
    }

    public function dspBotUser()
    {
        return $this->belongsTo(BotUser::class, 'dsp_bot_user_id');
    }

    public function qcBotUser()
    {
        return $this->belongsTo(BotUser::class, 'qc_bot_user_id');
    }

    public function isPickedUpOntime()
    {
        return $this->pickup_status == 'Ontime';
    }

    public function isDeliveredOntime()
    {
        return $this->delivery_status == 'Ontime';
    }

    public function isNotPickedUpOntime()
    {
        return $this->pickup_status == 'Late';
    }

    public function isNotDeliveredOntime()
    {
        return $this->delivery_status == 'Late';
    }

    public function getQcFullNameAttribute()
    {
        $name = '-';
        $botUser = $this->qcBotUser;
        if ($botUser && $botUser->botUserInfo) {
            $name = $botUser->botUserInfo->full_name;
        }
        return $name;
    }

    public function getDspFullNameAttribute()
    {
        $name = '-';
        $botUser = $this->dspBotUser;
        if ($botUser && $botUser->botUserInfo) {
            $name = $botUser->botUserInfo->full_name;
        }
        return $name;
    }

    public function getAssignedDspFullNameAttribute()
    {
        $name = '-';
        $botUser = $this->assignedDspBotUser;
        if ($botUser && $botUser->botUserInfo) {
            $name = $botUser->botUserInfo->full_name;
        }
        return $name;
    }

    public function getLoadAndPcsAttribute()
    {
        return $this->load_id . ' (' . $this->pcs_number . ')';
    }

    public static function types()
    {
        return [
            static::TYPE_MARKET_SPOT => __('Market load (spot)'),
            static::TYPE_MARKET_DEDICATED => __('Market load (dedicated)'),
            static::TYPE_AMAZON_SPOT => __('Amazon load (spot)'),
            static::TYPE_AMAZON_DEDICATED => __('Amazon load (dedicated)'),
            static::TYPE_LOAD_REPOWERED_SELF_TRUCK => __('Load repowered (self-truck)'),
            static::TYPE_LOAD_REPOWERED_THIRD_PARTY => __('Load repowered (third party)'),
            static::TYPE_LOAD_RECOVERED_SELF_TRUCK => __('Load recovered (self-truck)'),
            static::TYPE_LOAD_RECOVERED_THIRD_PARTY => __('Load recovered (third party)'),
        ];
    }

    public function getTypeTitleAttribute()
    {
        return static::types()[$this->type] ?? '-';
    }

    public static function statuses()
    {
        return [
            static::STATUS_CREATED => __('Created'),
            static::STATUS_RECONFIRMED => __('Reconfirmed'),
            static::STATUS_CANCELLED => __('Cancelled'),
        ];
    }

    public function getStatusTitleAttribute()
    {
        return static::statuses()[$this->status] ?? '-';
    }

    public function setCancelled()
    {
        $this->status = static::STATUS_CANCELLED;
        $this->save();
    }

    public function isCancelled()
    {
        return $this->status == static::STATUS_CANCELLED;
    }

    public function generateInfoTelegram()
    {
        $text = '';
        $text .= __('DSP') . ': ' . $this->dsp_full_name . PHP_EOL;
        $text .= __('Type') . ': ' . $this->type_title . PHP_EOL;
        $text .= __('Company code') . ': ' . $this->company_code . PHP_EOL;
        $text .= __('Load ID') . ': ' . $this->load_id . PHP_EOL;
        $text .= __('PCS number') . ': ' . $this->pcs_number . PHP_EOL;
        $text .= __('Rate') . ': ' . $this->rate . PHP_EOL;

        $text .= __('Authorized loaded mile') . ': ' . $this->authorized_loaded_mile . PHP_EOL;
        $text .= __('Load DH mile') . ': ' . $this->deadhead_mile . PHP_EOL;
        $text .= __('Authorized mile (PLD, TRL, FLT miles)') . ': ' . $this->authorized_mile . PHP_EOL;
        $text .= __('Unauthorized miles (including Home DH miles)') . ': ' . $this->unauthorized_mile . PHP_EOL;

        $text .= __('PU address (full)') . ': ' . $this->pickup_location . PHP_EOL;
        $text .= __('PU time Rate CON') . ': ' . ($this->pickup_time ? Helper::formatDateTime($this->pickup_time) : '-') . PHP_EOL;

resources/views/drivers-board.blade.php
@extends('layouts.app')

@section('title', __('Drivers board'))

@section('content')
    <div class="container-fluid">

        <h1>
            {{ __('Drivers board') }}
        </h1>

        <div class="my-4">
            <h4>{{ Helper::formatDate($weekStart) }} - {{ Helper::formatDate($weekEnd) }}</h4>
            <form action="{{ route('drivers-board') }}" id="drivers-board-filter-form">

                <div class="row">
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <label for="form_team_id">{{ __('Team') }}</label>
                            <select class="form-control selectpicker" data-live-search="true" name="team_id" id="form_team_id"
                                onchange="document.getElementById('drivers-board-filter-form').submit()">
                                <option value="">{{ __('All') }}</option>
                                @foreach ($teams as $team)
                                    <option value="{{ $team->id }}" @if ((string) $team->id == $filter['team_id']) selected @endif>
                                        {{ $team->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <label for="form_dispatcher_id">{{ __('Dispatcher') }}</label>
                            <select class="form-control selectpicker" data-live-search="true" name="dispatcher_id"
                                id="form_dispatcher_id"
                                onchange="document.getElementById('drivers-board-filter-form').submit()">
                                <option value="">{{ __('All') }}</option>
                                @foreach ($dispatchersList as $dispatcher)
                                    <option value="{{ $dispatcher->id }}"
                                        @if ((string) $dispatcher->id == $filter['dispatcher_id']) selected @endif>{{ $dispatcher->full_name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <label for="form_year">{{ __('Year') }}</label>
                            <select class="form-control selectpicker" name="year" id="form_year"
                                onchange="document.getElementById('drivers-board-filter-form').submit()">
                                @foreach ($years as $value)
                                    <option value="{{ $value }}" @if ((string) $value == $filter['year']) selected @endif>
                                        {{ $value }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <label for="form_week">{{ __('Week') }}</label>
                            <select class="form-control" name="week" id="form_week"
                                onchange="document.getElementById('drivers-board-filter-form').submit()">
                                @foreach ($weeks as $value)
                                    @php
                                        $date = now()->setISODate($filter['year'], $value);
                                    @endphp
                                    <option value="{{ $value }}" @if ((string) $value == $filter['week']) selected @endif>
                                        {{ $value }} / {{ Helper::formatDate($date->startOfWeek()) }} -
                                        {{ Helper::formatDate($date->endOfWeek()) }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="my-4">
            <div class="table-responsive">
                <table class="table table-bordered table-light table-hover">
                    <tr class="table-active">
                        <th>
                            {{ __('ID') }}
                        </th>
                        <th>
                            {{ __('Name') }}
                        </th>
                        <th>
                            {{ __('Main dispatcher') }}
                        </th>

                        <th>
                            {{ __('Weekly target $') }}
                        </th>
                        <th>
                            {{ __('Total $') }}
                        </th>

                        <th>
                            {{ __('Weekly target mile') }}
                        </th>
                        <th>
                            {{ __('Total mile') }}
                        </th>
                        <th>
                            {{ __('Per mile') }}
                        </th>
                    </tr>
                    @forelse($driverPlans as $driverPlan)
                        <tr class="@if($driverPlan->mile < $driverPlan->target_mile) text-danger @endif">
                            <td>{{ $driverPlan->driver->id }}</td>
                            <td>{{ $driverPlan->driver->name }}</td>
                            <td>{{ $driverPlan->driver->dispatcher_name }}</td>

                            <td>
                                {{ Helper::formatPrice($driverPlan->target) }}
                            </td>
                            <td>
                                {{ Helper::formatPrice($driverPlan->total) }}
                            </td>

                            <td>
                                {{ $driverPlan->target_mile }}
                            </td>
                            <td>
                                {{ $driverPlan->mile }}
                            </td>
                            <td>
                                {{ Helper::formatPrice($driverPlan->per_mile) }}
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="8" class="text-center">{{ __('Nothing found') }}</td>
                        </tr>
                    @endforelse
                </table>
            </div>
        </div>

        {{-- @php
            $teamsList = $teams;
            if ($filter['team_id']) {
                $teamsList = $teamsList->where('id', $filter['team_id']);
            }
        @endphp
        @foreach ($teamsList as $team)
            @php
                $driverPlansList = $driverPlans->where('team_id', $team->id);
            @endphp
            @if ($driverPlansList->isNotEmpty())
                <div class="my-5">
                    <h2 class="bg-dark text-white m-0 p-3" >{{ __('Team') }} {{ $team->name }}</h2>
                    @foreach ($driverPlansList as $driverPlan)
                        @if ($dispatcher->botUser && $dispatcher->botUser->drivers->isNotEmpty())
                            @include('partials.')
                        @endif
                    @endforeach
                </div>
            @endif
        @endforeach --}}


    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-header">{{ __('Dashboard') }}</div>
                    <div class="card-body">
                        @include('partials.alerts')
                        <div class="my-4">
                            <h3>{{ Auth::user()->name }} | {{ Auth::user()->role_name }}</h3>
                            @php
                                $botUserInfo = auth()->user()->botUserInfo;
                            @endphp
                            @if ($botUserInfo)
                                <div>
                                    {{ __('Position') }}: {{ $botUserInfo->position }}
                                </div>
                                <div>
                                    {{ __('Shift') }}: {{ $botUserInfo->shift }}
                                </div>
                                <div>
                                    {{ __('Team') }}: {{ $botUserInfo->team_name }}
                                </div>
                            @endif
                        </div>
                        @auth
                            <div class="my-4">
                                @if (Auth::user()->isAdmin())
                                    <a class="btn btn-lg btn-info mb-1" href="{{ route('board') }}">{{ __('Board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('team-sheet') }}">{{ __('Team sheet') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('kpi-board') }}">{{ __('KPI board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('drivers-board') }}">{{ __('Drivers board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('loads.index') }}">{{ __('Loads') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('drivers.index') }}">{{ __('Drivers') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('driver-statuses.index') }}">{{ __('Driver statuses') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('trailers.index') }}">{{ __('Trailers') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('teams.index') }}">{{ __('Teams') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('bot-user-info.index') }}">{{ __('Bot users') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('users.index') }}">{{ __('Users') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('settings.index') }}">{{ __('Settings') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('profile.index') }}">{{ __('Profile') }}</a>
                                @elseif (Auth::user()->isManager())
                                    <a class="btn btn-lg btn-info mb-1" href="{{ route('board') }}">{{ __('Board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('team-sheet') }}">{{ __('Team sheet') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('kpi-board', ['team_id' => Auth::user()->botUserInfo->team_id ?? '']) }}">{{ __('KPI board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('profile.index') }}">{{ __('Profile') }}</a>
                                @elseif (Auth::user()->isDsp())
                                    <a class="btn btn-lg btn-info mb-1" href="{{ route('board') }}">{{ __('Board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('team-sheet') }}">{{ __('Team sheet') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('kpi-board', ['dispatcher_id' => Auth::user()->botUserInfo->id ?? '']) }}">{{ __('KPI board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('profile.index') }}">{{ __('Profile') }}</a>
                                @elseif (Auth::user()->isUser())
                                    <a class="btn btn-lg btn-info mb-1" href="{{ route('board') }}">{{ __('Board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('team-sheet') }}">{{ __('Team sheet') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('kpi-board') }}">{{ __('KPI board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('profile.index') }}">{{ __('Profile') }}</a>
                                @elseif (Auth::user()->isQc())
                                    <a class="btn btn-lg btn-info mb-1" href="{{ route('board') }}">{{ __('Board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('team-sheet') }}">{{ __('Team sheet') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('kpi-board') }}">{{ __('KPI board') }}</a>
                                    <a class="btn btn-lg btn-info mb-1"
                                        href="{{ route('profile.index') }}">{{ __('Profile') }}</a>
                                @endif
                            </div>
                        @endauth
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-header">{{ __('Driver group hashtags') }}</div>
                    <div class="card-body">
                        @foreach (Helper::groupHashtagMessages() as $key => $value)
                        <div class="mb-3">
                            <strong>{{ $key }}</strong> <br>
                            {!! nl2br($value) !!}
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection