routes/web.php
<?php

use App\Http\Controllers\ArtisanController;
use App\Http\Controllers\BotUserInfoController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\DriverStatusController;
use App\Http\Controllers\Dsp\LoadController as DspLoadController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LoadController;
use App\Http\Controllers\PaymentGatewayController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StatsController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TelegramBotController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TrailerController;
use App\Http\Controllers\UserController;
use App\Http\Middleware\IsAdmin;
use App\Http\Middleware\IsDsp;
use App\Http\Middleware\IsManager;
use App\Http\Middleware\IsQc;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// telegram bot
Route::post('telegram-bot-r91zh779lfm7h8tq', [TelegramBotController::class, 'index'])->name('telegram-bot');
Route::get('telegram-bot/sethook-r91zh779lfm7h8tq', [TelegramBotController::class, 'sethook'])->name('telegram-bot.sethook');
Route::get('telegram-bot/deletehook-r91zh779lfm7h8tq', [TelegramBotController::class, 'deletehook'])->name('telegram-bot.deletehook');

// Payment
Route::post('paycom-emkooolkztfbzciw', [PaymentGatewayController::class, 'paycom'])->name('payment-gateway.paycom');
Route::any('click-pnhhqhfniksaejcn/prepare', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.prepare');
Route::any('click-pnhhqhfniksaejcn/complete', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.complete');

// Test
Route::get('test', [TestController::class, 'index']);

// report
Route::get('loads/report/daily-d778a0jdb29r', [LoadController::class, 'report'])->name('loads.report.daily.public');

Route::group(['middleware' => ['auth']], function () {

    // common routes
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('profile/update/password', [ProfileController::class, 'updatePassword'])->name('profile.update.password');

    // admin routes
    Route::group(['middleware' => [IsAdmin::class]], function () {
        Route::get('stats/drivers', [StatsController::class, 'drivers'])->name('stats.drivers');
        Route::resource('bot-user-info', BotUserInfoController::class);
        Route::resource('teams', TeamController::class);
        Route::resource('trailers', TrailerController::class);
        Route::get('drivers/{driver}/stats', [DriverController::class, 'stats'])->name('drivers.stats');
        Route::get('drivers/{driver}/history', [DriverController::class, 'history'])->name('drivers.history');
        Route::resource('drivers', DriverController::class);
        Route::get('loads', [LoadController::class, 'index'])->name('loads.index');
        Route::delete('loads/{load}', [LoadController::class, 'destroy'])->name('loads.destroy');
        Route::get('loads/download', [LoadController::class, 'download'])->name('loads.download');
        Route::get('loads/report', [LoadController::class, 'report'])->name('loads.report');

        Route::get('driver-statuses', [DriverStatusController::class, 'index'])->name('driver-statuses.index');
        Route::get('driver-statuses/{driverStatus}/edit', [DriverStatusController::class, 'edit'])->name('driver-statuses.edit');
        Route::put('driver-statuses/{driverStatus}', [DriverStatusController::class, 'update'])->name('driver-statuses.update');
        Route::delete('driver-statuses/{driverStatus}', [DriverStatusController::class, 'destroy'])->name('driver-statuses.destroy');

        Route::resource('users', UserController::class);
        Route::post('images', [ImageController::class, 'store'])->name('images.store');
        Route::resource('settings', SettingController::class);
    });

    // manager routes
    Route::group(['middleware' => [IsManager::class]], function () {
        //
    });

    // dsp routes
    Route::group(['middleware' => [IsDsp::class]], function () {
        //
    });

    // qc routes
    Route::group(['middleware' => [IsQc::class]], function () {
        //
    });

    // common boards
    Route::get('board', [HomeController::class, 'board'])->name('board');
    Route::get('team-sheet', [HomeController::class, 'teamSheet'])->name('team-sheet');
    Route::get('kpi-board', [HomeController::class, 'kpiBoard'])->name('kpi-board');
    Route::get('drivers-board', [HomeController::class, 'driversBoard'])->name('drivers-board');

    // loads
    Route::get('loads/{load}/cancel', [LoadController::class, 'cancelCreate'])->name('loads.cancel');
    Route::post('loads/{load}/cancel', [LoadController::class, 'cancelStore']);
    Route::get('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmCreate'])->name('loads.edit.confirm');
    Route::put('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmStore']);
    Route::get('loads/{load}', [LoadController::class, 'show'])->name('loads.show');
    Route::get('loads/{load}/edit', [LoadController::class, 'edit'])->name('loads.edit');
    Route::put('loads/{load}', [LoadController::class, 'update'])->name('loads.update');

    // artisan
    Route::get('artisan/migrate', [ArtisanController::class, 'migrate']);
    Route::get('artisan/driver/status-update', [ArtisanController::class, 'driverStatusUpdate']);
    Route::get('artisan/driver/create-weekly-plan', [ArtisanController::class, 'driverCreateWeeklyPlan']);
});

Auth::routes(['register' => false, 'reset' => false]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasFactory, HasApiTokens;

    const ROLE_ADMIN = 1;
    const ROLE_DSP = 2;
    const ROLE_QC = 3;
    const ROLE_MANAGER = 4;
    const ROLE_USER = 5;
    const ROLE_INS = 6;
    const ROLE_FLT = 7;
    const ROLE_TRL = 8;
    const ROLE_EQ = 9;
    const ROLE_ACCT = 10;
    const ROLE_SFT = 11;
    const ROLE_ELD = 12;
    const ROLE_IT = 13;
    const ROLE_MKTG = 14;
    const ROLE_OPS = 15;
    const ROLE_HR = 16;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone_number', 'role_id', 'bot_user_info_id', 'active',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    public static function roles()
    {
        return [
            static::ROLE_ADMIN => __('Admin'),
            static::ROLE_DSP => __('DSP'),
            static::ROLE_QC => __('QC'),
            static::ROLE_MANAGER => __('Manager'),
            static::ROLE_USER => __('User'),
            static::ROLE_INS => __('Insurance'),
            static::ROLE_FLT => __('Fleet'),
            static::ROLE_TRL => __('Trailer'),
            static::ROLE_EQ => __('Equipment'),
            static::ROLE_ACCT => __('Accounting'),
            static::ROLE_SFT => __('Safety'),
            static::ROLE_ELD => __('Safety ELD'),
            static::ROLE_IT => __('Information Technologies'),
            static::ROLE_MKTG => __('Marketing'),
            static::ROLE_OPS => __('Operations managers'),
            static::ROLE_HR => __('Human resources'),
        ];
    }

    public function isAdmin()
    {
        return $this->role_id == static::ROLE_ADMIN;
    }

    public function isManager()
    {
        return $this->role_id == static::ROLE_MANAGER;
    }

    public function isDsp()
    {
        return $this->role_id == static::ROLE_DSP;
    }

    public function isQc()
    {
        return $this->role_id == static::ROLE_QC;
    }

    public function isUser()
    {
        return $this->role_id == static::ROLE_USER;
    }

    public function botUserInfo() {
        return $this->belongsTo(BotUserInfo::class);
    }

    public function getRoleNameAttribute()
    {
        return static::roles()[$this->role_id] ?? __('No role');
    }

    public function hasPermission($permission)
    {
        if ($this->isAdmin()) {
            return true;
        }
        $permissions = [
            static::ROLE_DSP => [
                'view_dsp_kpi_board'
            ]
        ];
        if (empty($permissions[$this->role_id])) {
            return false;
        }
        return in_array($permission, $permissions[$this->role_id]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Helper;
use App\Models\BotUser;
use App\Models\BotUserInfo;
use App\Models\Changelog;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use stdClass;

class UserController extends Controller
{
    private $page = '/users';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $this->getFilter($request);
        $query = $this->generateQuery($request);
        $users = $query->paginate(50);
        return view('users.index', compact('users', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
        $botUsers = BotUser::whereHas('botUserInfo.botUser')->orderBy('first_name')->get();
        $roles = User::roles();
        return view('users.create', compact('user', 'botUsers', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validatedData($request);
        $data['active'] = !empty($data['active']) ? 1 : 0;
        $data['password'] = Hash::make($data['password']);
        $data['phone_number'] = $data['bot_user_info_id'] . mt_rand(100000, 999999);
        $user = User::create($data);
        return redirect($this->page)->with('success', 'User saved');
    }

    /**
     * Display the specified resource.
     *
     * @param int
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $botUsers = BotUser::whereHas('botUserInfo')->orderBy('first_name')->get();
        $roles = User::roles();
        return view('users.edit', compact('user', 'botUsers', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = $this->validatedData($request, $user);
        $data['active'] = !empty($data['active']) ? 1 : 0;
        if (!empty($data['password'])) {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }
        $user->update($data);
        return redirect($this->page)->with('success', 'User saved');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect($this->page)->with('success', 'User deleted');
    }

    private function validatedData(Request $request, User $user = null)
    {
        $validation = [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users,email',
            'password' => 'required|max:255',
            'bot_user_info_id' => 'required|exists:bot_user_info,id',
            'role_id' => 'required|in:' . implode(',', array_keys(User::roles())),
            'active' => '',
        ];
        if ($user) {
            $validation['password'] = 'max:255';
            $validation['email'] .= ',' . $user->id;
        }
        return $request->validate($validation);
    }

    private function generateQuery(Request $request)
    {
        $filter = $this->getFilter($request);
        $query = User::orderBy('id', 'desc');
        foreach ($filter as $key => $value) {
            if ($value === '' || $value === null || $value === '-') {
                continue;
            }
            if (in_array($key, ['name', 'email'])) {
                $query->where($key, 'LIKE', '%' . $value . '%');
            }
        }
        $query->with(['botUserInfo']);
        return $query;
    }

    private function getFilter(Request $request)
    {
        $filter = [
            'name' => $request->input('name', ''),
            'email' => $request->input('email', ''),
        ];
        return $filter;
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', __('Add user'))

@section('content')
    <div class="container">

        <h1>{{ __('Add user') }}</h1>

        <div class="py-4">
            <a href="{{ (url()->previous() && url()->previous() != url()->current()) ? url()->previous() : route('users.index') }}" class="btn btn-info">{{ __('Back') }}</a>
        </div>

        <form action="{{ route('users.store') }}" method="POST">

            @csrf

            @include('users.partials.form')

            <div class="form-group">
                <button class="btn btn-lg btn-success" type="submit">{{ __('Save') }}</button>
            </div>
        </form>

    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', __('Edit user'))

@section('content')
    <div class="container">

        <h1>{{ __('Edit user') }}</h1>

        <div class="py-4">
            <a href="{{ (url()->previous() && url()->previous() != url()->current()) ? url()->previous() : route('users.index') }}" class="btn btn-info">{{ __('Back') }}</a>
        </div>

        <form action="{{ route('users.update', $user->id) }}" method="POST">

            @csrf
            @method('PUT')

            @include('users.partials.form')

            <div class="form-group">
                <button class="btn btn-lg btn-success" type="submit">{{ __('Save') }}</button>
            </div>
        </form>

    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', __('Users'))

@section('content')
    <div class="container">

        @include('partials.alerts')

        <div class="my-4">
            <a href="{{ route('users.create') }}" class="btn btn-lg btn-info">
                {{ __('Add user') }}
            </a>
        </div>

        <h1>{{ __('Users') }}</h1>

        <div class="my-4">
            <form action="{{ route('users.index') }}" id="users-filter-form">

                <div class="row">
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <div class="form-group">
                                <label for="form_name">{{ __('Name') }}</label>
                                <input type="text" id="form_name" name="name" class="form-control"
                                    value="{{ $filter['name'] }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="form-group">
                            <div class="form-group">
                                <label for="form_email">{{ __('E-mail') }}</label>
                                <input type="text" id="form_email" name="email" class="form-control"
                                    value="{{ $filter['email'] }}">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <button class="btn btn-primary" type="submit">{{ __('Apply filter') }}</button>
                </div>
            </form>
        </div>

        <div class="my-4">
            <div class="table-responsive">
                <table class="table table-bordered table-light table-hover">
                    <tr class="table-active">
                        <th>
                            {{ __('ID') }}
                        </th>
                        <th>
                            {{ __('E-mail') }}
                        </th>
                        <th>
                            {{ __('Name') }}
                        </th>
                        <th>
                            {{ __('Bot user') }}
                        </th>
                        <th>
                            {{ __('Role') }}
                        </th>
                        <th>
                            {{ __('Active') }}
                        </th>
                        <th></th>
                    </tr>
                    @forelse($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->botUserInfo->full_name ?? '' }}</td>
                            <td>{{ $user->role_name }}</td>
                            <td>{{ $user->active ? __('Yes') : __('No') }}</td>
                            <td class="text-nowrap">
                                <a href="{{ route('users.edit', ['user' => $user->id]) }}"
                                    class="btn btn-sm btn-warning">{{ __('Edit') }}</a>
                                <a href="#" onclick="event.preventDefault(); if (confirm('{{ __('Are you sure?') }}')) { $('#delete-user-{{ $user->id }}').submit() }" class="btn btn-sm btn-danger">{{ __('Delete') }}</a>
                                <form action="{{ route('users.destroy', ['user' => $user->id]) }}" method="post" id="delete-user-{{ $user->id }}">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="8" class="text-center">{{ __('Nothing found') }}</td>
                        </tr>
                    @endforelse
                </table>
            </div>
            {{ $users->withQueryString()->links() }}
        </div>


        <br>
        <br>
        <br>
        <br>
        <br>

    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('title', __('User') . '#' . $user)

@section('content')
    <div class="container">

    	<h1>
    		{{ __('Driver') }} #{{ $user }}
    	</h1>

        <div class="py-4 d-print-none">
            <a href="{{ (url()->previous() && url()->previous() != url()->current()) ? url()->previous() : route('users.index') }}" class="btn btn-info">{{ __('Back') }}</a>
        </div>

    </div>
@endsection