routes/web.php
<?php

use App\Http\Controllers\ArtisanController;
use App\Http\Controllers\BotUserInfoController;
use App\Http\Controllers\DriverController;
use App\Http\Controllers\DriverStatusController;
use App\Http\Controllers\Dsp\LoadController as DspLoadController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LoadController;
use App\Http\Controllers\PaymentGatewayController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StatsController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TelegramBotController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TrailerController;
use App\Http\Controllers\UserController;
use App\Http\Middleware\IsAdmin;
use App\Http\Middleware\IsDsp;
use App\Http\Middleware\IsManager;
use App\Http\Middleware\IsQc;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// telegram bot
Route::post('telegram-bot-r91zh779lfm7h8tq', [TelegramBotController::class, 'index'])->name('telegram-bot');
Route::get('telegram-bot/sethook-r91zh779lfm7h8tq', [TelegramBotController::class, 'sethook'])->name('telegram-bot.sethook');
Route::get('telegram-bot/deletehook-r91zh779lfm7h8tq', [TelegramBotController::class, 'deletehook'])->name('telegram-bot.deletehook');

// Payment
Route::post('paycom-emkooolkztfbzciw', [PaymentGatewayController::class, 'paycom'])->name('payment-gateway.paycom');
Route::any('click-pnhhqhfniksaejcn/prepare', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.prepare');
Route::any('click-pnhhqhfniksaejcn/complete', [PaymentGatewayController::class, 'click'])->name('payment-gateway.click.complete');

// Test
Route::get('test', [TestController::class, 'index']);

// report
Route::get('loads/report/daily-d778a0jdb29r', [LoadController::class, 'report'])->name('loads.report.daily.public');

Route::group(['middleware' => ['auth']], function () {

    // common routes
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::post('profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('profile/update/password', [ProfileController::class, 'updatePassword'])->name('profile.update.password');

    // admin routes
    Route::group(['middleware' => [IsAdmin::class]], function () {
        Route::get('stats/drivers', [StatsController::class, 'drivers'])->name('stats.drivers');
        Route::resource('bot-user-info', BotUserInfoController::class);
        Route::resource('teams', TeamController::class);
        Route::resource('trailers', TrailerController::class);
        Route::get('drivers/{driver}/stats', [DriverController::class, 'stats'])->name('drivers.stats');
        Route::get('drivers/{driver}/history', [DriverController::class, 'history'])->name('drivers.history');
        Route::resource('drivers', DriverController::class);
        Route::get('loads', [LoadController::class, 'index'])->name('loads.index');
        Route::delete('loads/{load}', [LoadController::class, 'destroy'])->name('loads.destroy');
        Route::get('loads/download', [LoadController::class, 'download'])->name('loads.download');
        Route::get('loads/report', [LoadController::class, 'report'])->name('loads.report');

        Route::get('driver-statuses', [DriverStatusController::class, 'index'])->name('driver-statuses.index');
        Route::get('driver-statuses/{driverStatus}/edit', [DriverStatusController::class, 'edit'])->name('driver-statuses.edit');
        Route::put('driver-statuses/{driverStatus}', [DriverStatusController::class, 'update'])->name('driver-statuses.update');
        Route::delete('driver-statuses/{driverStatus}', [DriverStatusController::class, 'destroy'])->name('driver-statuses.destroy');

        Route::resource('users', UserController::class);
        Route::post('images', [ImageController::class, 'store'])->name('images.store');
        Route::resource('settings', SettingController::class);
    });

    // manager routes
    Route::group(['middleware' => [IsManager::class]], function () {
        //
    });

    // dsp routes
    Route::group(['middleware' => [IsDsp::class]], function () {
        //
    });

    // qc routes
    Route::group(['middleware' => [IsQc::class]], function () {
        //
    });

    // common boards
    Route::get('board', [HomeController::class, 'board'])->name('board');
    Route::get('team-sheet', [HomeController::class, 'teamSheet'])->name('team-sheet');
    Route::get('kpi-board', [HomeController::class, 'kpiBoard'])->name('kpi-board');
    Route::get('drivers-board', [HomeController::class, 'driversBoard'])->name('drivers-board');

    // loads
    Route::get('loads/{load}/cancel', [LoadController::class, 'cancelCreate'])->name('loads.cancel');
    Route::post('loads/{load}/cancel', [LoadController::class, 'cancelStore']);
    Route::get('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmCreate'])->name('loads.edit.confirm');
    Route::put('loads/{load}/edit/confirm', [LoadController::class, 'editConfirmStore']);
    Route::get('loads/{load}', [LoadController::class, 'show'])->name('loads.show');
    Route::get('loads/{load}/edit', [LoadController::class, 'edit'])->name('loads.edit');
    Route::put('loads/{load}', [LoadController::class, 'update'])->name('loads.update');

    // artisan
    Route::get('artisan/migrate', [ArtisanController::class, 'migrate']);
    Route::get('artisan/driver/status-update', [ArtisanController::class, 'driverStatusUpdate']);
    Route::get('artisan/driver/create-weekly-plan', [ArtisanController::class, 'driverCreateWeeklyPlan']);
});

Auth::routes(['register' => false, 'reset' => false]);

app/Models/Load.php
<?php

namespace App\Models;

use App\Helpers\Helper;
use App\Services\TelegramService;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Load extends Model
{
    use HasFactory;

    const TYPE_MARKET_SPOT = 0;
    const TYPE_AMAZON_SPOT = 1;
    const TYPE_MARKET_DEDICATED = 2;
    const TYPE_AMAZON_DEDICATED = 3;
    const TYPE_LOAD_REPOWERED_SELF_TRUCK = 4;
    const TYPE_LOAD_REPOWERED_THIRD_PARTY = 5;
    const TYPE_LOAD_RECOVERED_SELF_TRUCK = 6;
    const TYPE_LOAD_RECOVERED_THIRD_PARTY = 7;

    const STATUS_OVERWRITTEN = -2;
    const STATUS_CANCELLED = -1;
    const STATUS_CREATED = 0;
    const STATUS_CONFIRMED = 1;
    const STATUS_RECONFIRMED = 2;

    const FILE_TYPE_PHOTO = 0;
    const FILE_TYPE_DOCUMENT = 1;

    const TRANSIT_MAX_DAYS = 3;

    protected $guarded = [];

    protected $casts = [
        'local_pickup_time' => 'datetime',
        'pickup_time' => 'datetime',
        'local_delivery_time' => 'datetime',
        'delivery_time' => 'datetime',
        'pickup_time_for_driver' => 'datetime',
        'delivery_time_for_driver' => 'datetime',
    ];

    protected static function booted()
    {
        static::saving(function ($load) {
            $load->mile = $load->countTotalMile();
            $load->total = $load->countTotalRate();
            $load->pickup_time = Helper::convertToBotTime($load->local_pickup_time, $load->pickup_timezone);
            $load->delivery_time = Helper::convertToBotTime($load->local_delivery_time, $load->delivery_timezone);

            $load->batch_number = Helper::getLoadBatchNumber($load);

            $pickupAddressParsed = Helper::parseAddress($load->pickup_location);
            $load->pickup_state_code = $pickupAddressParsed['state'];
            $load->pickup_zip_code = $pickupAddressParsed['zip'];

            $deliveryAddressParsed = Helper::parseAddress($load->delivery_location);
            $load->delivery_state_code = $deliveryAddressParsed['state'];
            $load->delivery_zip_code = $deliveryAddressParsed['zip'];
        });

        static::created(function ($load) {
            // send notification to history group
            $telegram = new TelegramService();
            // send file photo/pdf
            $historyGroupChatId = Helper::setting('history_group');
            if ($load->file_type == Load::FILE_TYPE_PHOTO) {
                $telegram->sendPhoto($historyGroupChatId, $load->file_id);
            } elseif ($load->file_type == Load::FILE_TYPE_DOCUMENT) {
                $telegram->sendDocumentById($historyGroupChatId, $load->file_id);
            }
            // send message
            $telegram->sendMessage($historyGroupChatId, $load->generateInfoTelegram());


            // send notifications to driver group (dispatch confirmation) #LoadID and #MileageInfo
            $dispatchConfirmationText = $load->dispatchInfoTelegram();
            $testingGroupChatId = Helper::setting('temporary_testing_group');
            $driverGroupChatId = $load->driver ? $load->driver->chat_id : null;
            $telegram->sendMessage($testingGroupChatId, $dispatchConfirmationText, 'HTML');
            if ($driverGroupChatId) {
                $telegram->sendMessage($driverGroupChatId, $dispatchConfirmationText, 'HTML');
            }
            $mileageInfoText = $load->mileageInfoTelegram();
            $telegram->sendMessage($testingGroupChatId, $mileageInfoText, 'HTML');
            if ($driverGroupChatId) {
                $telegram->sendMessage($driverGroupChatId, $mileageInfoText, 'HTML');
            }

            /**#MileageInfo
Batch No.: 328

Authorized loaded mile:
DH mile:
Other miles:
______________________________
Total miles:

@DriverName
 */

        });
        static::saved(function ($load) {
            // update driver status after cancelled
            if ($load->cancel_time) {
                if ($load->cancel_time <= $load->pickup_time) {
                    DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_TRANSIT)->delete();
                } elseif ($load->cancel_time > $load->pickup_time && $load->cancel_time < $load->delivery_time) {
                    DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_TRANSIT)->update([
                        'end_time' => $load->cancel_time,
                    ]);
                }
            }

            // update transit driver status if pickup_time and
            $transitDriverStatus = DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_TRANSIT)->latest()->first();
            if ($transitDriverStatus) {
                $transitDriverStatus->start_time = $load->pickup_time;
                $transitDriverStatus->end_time = $load->delivery_time;
                $transitDriverStatus->saveQuietly();
            }
            $dispatchedDriverStatus = DriverStatus::where('driver_id', $load->driver_id)->where('load_id', $load->id)->where('status', DriverStatus::STATUS_DISPATCHED)->latest()->first();
            if ($dispatchedDriverStatus) {
                $dispatchedDriverStatus->end_time = $load->pickup_time;
                $dispatchedDriverStatus->saveQuietly();
            }
        });
    }

    public function driver()
    {
        return $this->belongsTo(Driver::class);
    }

    public function mainTrailer()
    {
        return $this->belongsTo(Trailer::class, 'trailer_id');
    }

    public function getDriverNameAttribute()
    {
        $name = '-';
        if ($this->driver) {
            $name = $this->driver->name;
        }
        return $name;
    }

    public function assignedDspBotUser()
    {
        return $this->belongsTo(BotUser::class, 'assigned_dsp_bot_user_id');
    }

    public function dspBotUser()
    {
        return $this->belongsTo(BotUser::class, 'dsp_bot_user_id');
    }

    public function qcBotUser()
    {
        return $this->belongsTo(BotUser::class, 'qc_bot_user_id');
    }

    public function isPickedUpOntime()
    {
        return $this->pickup_status == 'Ontime';
    }

    public function isDeliveredOntime()
    {
        return $this->delivery_status == 'Ontime';
    }

    public function isNotPickedUpOntime()
    {
        return $this->pickup_status == 'Late';
    }

    public function isNotDeliveredOntime()
    {
        return $this->delivery_status == 'Late';
    }

    public function getQcFullNameAttribute()
    {
        $name = '-';
        $botUser = $this->qcBotUser;
        if ($botUser && $botUser->botUserInfo) {
            $name = $botUser->botUserInfo->full_name;
        }
        return $name;
    }

    public function getDspFullNameAttribute()
    {
        $name = '-';
        $botUser = $this->dspBotUser;
        if ($botUser && $botUser->botUserInfo) {
            $name = $botUser->botUserInfo->full_name;
        }
        return $name;
    }

    public function getAssignedDspFullNameAttribute()
    {
        $name = '-';
        $botUser = $this->assignedDspBotUser;
        if ($botUser && $botUser->botUserInfo) {
            $name = $botUser->botUserInfo->full_name;
        }
        return $name;
    }

    public function getLoadAndPcsAttribute()
    {
        return $this->load_id . ' (' . $this->pcs_number . ')';
    }

    public static function types()
    {
        return [
            static::TYPE_MARKET_SPOT => __('Market load (spot)'),
            static::TYPE_MARKET_DEDICATED => __('Market load (dedicated)'),
            static::TYPE_AMAZON_SPOT => __('Amazon load (spot)'),
            static::TYPE_AMAZON_DEDICATED => __('Amazon load (dedicated)'),
            static::TYPE_LOAD_REPOWERED_SELF_TRUCK => __('Load repowered (self-truck)'),
            static::TYPE_LOAD_REPOWERED_THIRD_PARTY => __('Load repowered (third party)'),
            static::TYPE_LOAD_RECOVERED_SELF_TRUCK => __('Load recovered (self-truck)'),
            static::TYPE_LOAD_RECOVERED_THIRD_PARTY => __('Load recovered (third party)'),
        ];
    }

    public function getTypeTitleAttribute()
    {
        return static::types()[$this->type] ?? '-';
    }

    public static function statuses()
    {
        return [
            static::STATUS_CREATED => __('Created'),
            static::STATUS_RECONFIRMED => __('Reconfirmed'),
            static::STATUS_CANCELLED => __('Cancelled'),
        ];
    }

    public function getStatusTitleAttribute()
    {
        return static::statuses()[$this->status] ?? '-';
    }

    public function setCancelled()
    {
        $this->status = static::STATUS_CANCELLED;
        $this->save();
    }

    public function isCancelled()
    {
        return $this->status == static::STATUS_CANCELLED;
    }

    public function generateInfoTelegram()
    {
        $text = '';
        $text .= __('DSP') . ': ' . $this->dsp_full_name . PHP_EOL;
        $text .= __('Type') . ': ' . $this->type_title . PHP_EOL;
        $text .= __('Company code') . ': ' . $this->company_code . PHP_EOL;
        $text .= __('Load ID') . ': ' . $this->load_id . PHP_EOL;
        $text .= __('PCS number') . ': ' . $this->pcs_number . PHP_EOL;
        $text .= __('Rate') . ': ' . $this->rate . PHP_EOL;

        $text .= __('Authorized loaded mile') . ': ' . $this->authorized_loaded_mile . PHP_EOL;
        $text .= __('Load DH mile') . ': ' . $this->deadhead_mile . PHP_EOL;
        $text .= __('Authorized mile (PLD, TRL, FLT miles)') . ': ' . $this->authorized_mile . PHP_EOL;
        $text .= __('Unauthorized miles (including Home DH miles)') . ': ' . $this->unauthorized_mile . PHP_EOL;

        $text .= __('PU address (full)') . ': ' . $this->pickup_location . PHP_EOL;
        $text .= __('PU time Rate CON') . ': ' . ($this->pickup_time ? Helper::formatDateTime($this->pickup_time) : '-') . PHP_EOL;

resources/views/loads/cancel.blade.php
@extends('layouts.app')

@section('title', __('Cancel load'))

@section('content')
    <div class="container">

        <h1>{{ __('Cancel load') }} <a href="{{ route('loads.show', [$load->id]) }}" target="_blank">{{ $load->load_and_pcs }}</a></h1>

        <form action="{{ route('loads.cancel', [$load->id]) }}" method="POST">

            @csrf

            <div class="form-group">
                <label for="form_tonu">{{ __('TONU') }}</label>
                <input type="number" name="tonu" id="form_tonu" class="form-control" value="{{ old('tonu') ?? 0 }}" required>
                @error('tonu')
                <div class="invalid-feedback d-block">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="form_cancel_time">{{ __('Cancel time (east time yyyy-mm-dd hh:mm)') }}</label>
                <input type="text" name="cancel_time" id="form_cancel_time"
                    class="form-control datetimepicker-standard"
                    value="{{ old('cancel_time') }}" required>
                @error('cancel_time')
                    <div class="invalid-feedback d-block">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="form_cancel_comment">{{ __('Comment') }}</label>
                <textarea type="number" name="cancel_comment" id="form_cancel_comment" class="form-control" required>{{ old('cancel_comment') }}</textarea>
                @error('cancel_comment')
                <div class="invalid-feedback d-block">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <button class="btn btn-lg btn-success" type="submit">{{ __('Save') }}</button>
            </div>
        </form>

    </div>
@endsection

resources/views/loads/show.blade.php
@extends('layouts.app')

@section('title', __('Load') . '#' . $load->load_id)

@section('content')
    <div class="container">

        @include('partials.alerts')

        <h1>
            {{ __('Load') }} {{ $load->load_id }}
        </h1>

        <div class="table-responsive">
            <table class="table table-bordered">
                <tr>
                    <td>
                        <strong>{{ __('Company code') }}</strong>
                    </td>
                    <td>
                        {{ $load->company_code }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Load ID') }}</strong>
                    </td>
                    <td>
                        {{ $load->load_id }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Type') }}</strong>
                    </td>
                    <td>
                        {{ $load->type_title }}
                    </td>
                </tr>
                {{-- <tr>
                    <td>
                        <strong>{{ __('Status') }}</strong>
                    </td>
                    <td>
                        {{ $load->status_title }}
                    </td>
                </tr> --}}
                <tr>
                    <td>
                        <strong>{{ __('Driver') }}</strong>
                    </td>
                    <td>
                        {{ $load->driver_name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Third company') }}</strong>
                    </td>
                    <td>
                        {{ $load->third_company }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('PCS number') }}</strong>
                    </td>
                    <td>
                        {{ $load->pcs_number }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Pickup status') }}</strong>
                    </td>
                    <td>
                        {{ $load->pickup_status }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Pickup QC comment') }}</strong>
                    </td>
                    <td>
                        {{ $load->pickup_qc_comment }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Delivery status') }}</strong>
                    </td>
                    <td>
                        {{ $load->delivery_status }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Delivery QC comment') }}</strong>
                    </td>
                    <td>
                        {{ $load->delivery_qc_comment }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Rate') }}</strong>
                    </td>
                    <td>
                        {{ $load->rate }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Mile') }}</strong>
                    </td>
                    <td>
                        {{ __('Authorized loaded mile') }}: {{ $load->authorized_loaded_mile }} <br>
                        {{ __('Load DH mile') }}: {{ $load->deadhead_mile }} <br>
                        {{ __('Authorized mile (PLD, TRL, FLT miles)') }}: {{ $load->authorized_mile }} <br>
                        {{ __('Unauthorized miles (including Home DH miles)') }}: {{ $load->unauthorized_mile }} <br>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('PU address (full)') }}</strong>
                    </td>
                    <td>
                        {{ $load->pickup_location }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('PU time') }}</strong>
                    </td>
                    <td>
                        {{ $load->pickup_time ? Helper::formatDateTime($load->pickup_time) : '-' }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Delivery address (full)') }}</strong>
                    </td>
                    <td>
                        {{ $load->delivery_location }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Delivery time') }}</strong>
                    </td>
                    <td>
                        {{ $load->delivery_time ? Helper::formatDateTime($load->delivery_time) : '-' }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Special note') }}</strong>
                    </td>
                    <td>
                        {{ $load->special_note }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Check in as') }}</strong>
                    </td>
                    <td>
                        {{ $load->check_in_as }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Trailer') }}</strong>
                    </td>
                    <td>
                        {{ $load->trailer }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Trailer note') }}</strong>
                    </td>
                    <td>
                        {{ $load->trailer_note }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Pickup address and time (2, 3, 4 Stops)') }}</strong>
                    </td>
                    <td>
                        {{ $load->pickup_additional_stops }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('DSP') }}</strong>
                    </td>
                    <td>
                        {{ $load->dsp_full_name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('DSP bonus') }}</strong>
                    </td>
                    <td>
                        {{ $load->dsp_bonus }} %
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('QC') }}</strong>
                    </td>
                    <td>
                        {{ $load->qc_full_name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Created') }}</strong>
                    </td>
                    <td>
                        {{ Helper::formatDateTime($load->created_at) }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>{{ __('Updated') }}</strong>
                    </td>
                    <td>
                        {{ Helper::formatDateTime($load->updated_at) }}
                    </td>
                </tr>
                @if ($load->isCancelled())
                    <tr>
                        <td>
                            <strong>{{ __('Status') }}</strong>
                        </td>
                        <td>
                            <div class="text-danger">{{ $load->status_title }}</div>
                            <div>{{ __('TONU') }}: {{ $load->tonu }}</div>
                            <div>{{ __('Comment') }}: {{ $load->cancel_comment }}</div>
                        </td>
                    </tr>
                @endif

                <tr class="d-print-none">
                    <td>
                        <strong>&nbsp;</strong>
                    </td>
                    <td>
                        @can('update-load', $load)
                            <a href='{{ route('loads.edit', [$load->id]) }}' class='text-info'
                                target='_blank'>{{ __('Edit') }}</a>
                        @endcan
                        @can('cancel-load', $load)
                            <a href='{{ route('loads.cancel', [$load->id]) }}' class='text-danger'
                                target='_blank'>{{ __('Cancel') }}</a>
                        @endcan
                        @can('delete-load', $load)
                            <a href="#"
                                onclick="event.preventDefault(); if (confirm('{{ __('Are you sure?') }}')) { $('#delete-load-{{ $load->id }}').submit() }"
                                class="text-danger">{{ __('Delete') }}</a>
                            <form action="{{ route('loads.destroy', ['load' => $load->id]) }}" method="post"
                                id="delete-load-{{ $load->id }}">
                                @csrf
                                @method('DELETE')
                            </form>
                        @endcan
                    </td>
                </tr>
            </table>
        </div>

        <div class="py-4 d-print-none">
            <a href="{{ url()->previous() && url()->previous() != url()->current() ? url()->previous() : route('loads.index') }}"
                class="btn btn-info">{{ __('Back') }}</a>
        </div>

    </div>
@endsection